---
- name: Install curl and gnupg
  apt:
    name:
      - curl
      - gnupg
    state: present
    update_cache: yes

- name: Download Jenkins GPG key and dearmor it
  shell: |
    curl -fsSL https://pkg.jenkins.io/debian/jenkins.io-2023.key | gpg --dearmor > /usr/share/keyrings/jenkins-keyring.gpg
  args:
    creates: /usr/share/keyrings/jenkins-keyring.gpg
    executable: /bin/bash

- name: Add Jenkins apt repository
  apt_repository:
    repo: "deb [signed-by=/usr/share/keyrings/jenkins-keyring.gpg] https://pkg.jenkins.io/debian binary/"
    state: present
    filename: jenkins

- name: Update apt cache
  apt:
    update_cache: yes

- name: Install Java
  apt:
    name: openjdk-17-jdk
    state: present

- name: Install Jenkins
  apt:
    name: jenkins
    state: present

- name: Ensure Jenkins is started and enabled
  service:
    name: jenkins
    enabled: yes
    state: started
